### ISSUE TITLE
cannot delete

### ISSUE THREAD

**Issue by gle42** [n-e/totoz.eu#44]
We used to be able to delete/update a totoz, but it's not possible anymore : the feature just does not exist

**Comment by n-e** [comment]
Je n'ai pas trop le temps de bosser là dessus mais je suis ouvert aux PR, et s'il y a un totoz particulier que tu veux supprimer/modifier je peux le faire à la mano

**Comment by gle42** [comment]
PR created https://github.com/n-e/totoz.eu/pull/45

**Comment by n-e** [comment]
closed by #45
